# .github/workflows/workflow.yml
name: CI WORKFLOW
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ISSUER: "CI Test"
  TOKEN_EXPIRE_TIME: "1800000"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      # Create the file your Utils loads in dev mode
      # Adjust filename/path if your Utils expects a different name.
      - name: Create test config.properties
        shell: bash
        run: |
          mkdir -p src/test/resources
          cat > src/test/resources/config.properties <<EOF
          SECRET_KEY=${SECRET_KEY}
          ISSUER=${ISSUER}
          TOKEN_EXPIRE_TIME=${TOKEN_EXPIRE_TIME}
          EOF
          echo "Wrote src/test/resources/config.properties"

      - name: Build with Maven
        run: mvn --batch-mode -DskipTests=false clean package

      # The steps below are for Docker deployment — comment them out for now
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/hotel_api:latest
